// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.runfun.domain;

import com.mycompany.runfun.domain.UserIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserIntegrationTest_Roo_Configurable {
    
    declare @type: UserIntegrationTest: @Configurable;
    
}
